// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "obmtfront2-20191210000619-hostingbucket-obmtenv",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://obmtfront2-20191210000619-hostingbucket-obmtenv.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
